name: Create rolling release

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  windows-libretro-build:
    runs-on: windows-2016
    steps:
    - uses: actions/checkout@v2.3.1
      with:
        fetch-depth: 0

    - name: Compile release build
      shell: cmd
      run: |
        call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" x64
        mkdir build
        cd build
        cmake -G Ninja -DCMAKE_BUILD_TYPE=Release -DBUILD_LIBRETRO_CORE=ON -DCMAKE_C_COMPILER:FILEPATH="%VCToolsInstallDir%\bin\HostX64\x64\cl.exe" -DCMAKE_CXX_COMPILER:FILEPATH="%VCToolsInstallDir%\bin\HostX64\x64\cl.exe" ..
        ninja
        
    - name: Create libretro core archive
      shell: cmd
      run: |
        cd build
        "C:\Program Files\7-Zip\7z.exe" a -r duckstation_libretro.dll.zip ./duckstation_libretro.dll

    - name: Upload release artifact
      uses: actions/upload-artifact@v1
      with:
        name: "windows-libretro-x64"
        path: "build/duckstation_libretro.dll.zip"
